name:                schnorr-cli
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/prolic/schnorr-cli#readme
license:             MIT
author:              Sascha-Oliver Prolic
maintainer:          saschaprolic@googlemail.com
copyright:           2022 Sascha-Oliver Prolic
#category:
extra-source-files:
- README.md

dependencies:
  - base
  - base16
  - bytestring
  - cryptohash-sha256
  - data-default
  - optparse-applicative
  - optparse-simple
  - secp256k1-schnorr
  - text

executables:
  schnorr:
    source-dirs:      src
    main:             Main.hs
    extra-libraries:  secp256k1
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
